[[repositories]]
type = "maven"
name = "sonatype-public"
url = "https://oss.sonatype.org/content/groups/public/"

[[repositories]]
type = "maven"
name = "aliyun-public"
url = "https://maven.aliyun.com/repository/public/"

#[[repositories]]
#type = "maven"
#name = "xxx-private"
#url = "https://xxx.xxx.xxx/repository/private/"
#username = "xxx"
#password = "xxx"