##############################
#         自定义仓库           #
##############################
# maven 仓库地址 次序由上到下
# 最前默认是本地仓库（file://./libraries/）

[[repositories]]
name = "sonatype-public"
url = "https://oss.sonatype.org/content/groups/public/"

[[repositories]]
name = "aliyun-public"
url = "https://maven.aliyun.com/repository/public/"

# 最后默认是 maven 中央仓库（https://repo1.maven.org/maven2/）