# 主版本号（major）：当存在兼容性变化时，主版本号 +1，次版本号和修订号清零
# 次版本号（minor）：当添加新功能时，次版本号 +1，修订号清零
# 修订号（revision）：当有漏洞被修复时，修订号 +1
# 版本号组成：major.minor.revision
[version]
major = 2
minor = 0
revision = 0

# 项目开发者信息
[[developers]]
id = "F2C2163FC18279C2"
name = "ketikai"
email = "ketikai@idealstate.team"

#[[developers]]
#name = "xxx"
#email = "xxx@xxx.xxx"
#key = "XXXXXXXXXXXXXXXX"